import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { HYBRID_4_EXPERIMENTAL_DIRECT_CAPABILITIES } from "../gateway/experimental/hybridProfile";

const root = resolve(import.meta.dir, "..");
const apiPath = resolve(root, "docs/api.json");
const outputPath = resolve(
  root,
  "gateway/experimental/generated/hybrid4Schemas.ts"
);

type ApiTool = {
  name: string;
  description: string;
  annotations?: Record<string, unknown>;
  parameters: Record<string, unknown>;
};

export async function generateHybrid4Schemas(): Promise<string> {
  const api = JSON.parse(await readFile(apiPath, "utf8")) as {
    tools: ApiTool[];
  };
  const selected = Object.fromEntries(
    HYBRID_4_EXPERIMENTAL_DIRECT_CAPABILITIES.map((name) => {
      const tool = api.tools.find((entry) => entry.name === name);
      if (!tool) {
        throw new Error(
          `Hybrid-4 capability "${name}" is missing from docs/api.json.`
        );
      }
      return [
        name,
        {
          description: tool.description,
          annotations: tool.annotations ?? {},
          inputSchema: tool.parameters,
        },
      ];
    })
  );

  return `// GENERATED by scripts/generate-hybrid4-schemas.ts from docs/api.json.
// Do not hand-edit.
export const HYBRID_4_GENERATED_SCHEMAS = ${JSON.stringify(selected, null, 2)} as const;
`;
}

if (import.meta.main) {
  await writeFile(outputPath, await generateHybrid4Schemas(), "utf8");
}
