import { describe, expect, test } from "bun:test";

async function source(path: string): Promise<string> {
  return Bun.file(path).text();
}

describe("Desktop control-plane ownership", () => {
  test("Desktop depends on canonical compatibility and managed distribution owners", async () => {
    const [rust, app, cli, workflow] = await Promise.all([
      source("../apps/desktop/src-tauri/src/system_status.rs"),
      source("../apps/desktop/src/App.svelte"),
      source("distribution/cli.ts"),
      source("../.github/workflows/desktop-verify.yml"),
    ]);

    expect(rust).toContain('../../../../mcp/compatibility/blockbench.json');
    expect(rust).toContain('"update" | "recover" | "repair" | "setup-tls"');
    expect(rust).toContain('.arg("install")');
    expect(rust).toContain('"resources/managed/blockit.exe"');
    expect(rust).toContain('"--plugin-path"');
    expect(rust).toContain('join("plugins").join("blockit_mcp.js")');
    expect(app).toContain("Show plugin file");
    expect(app).toContain("Setup Runtime Security");
    expect(app).toContain("Update managed components");
    expect(app).toContain("tls_ready");
    expect(app).toContain("'update' | 'recover' | 'repair'");
    for (const command of ["update", "recover", "repair", "status", "mcp"]) {
      expect(cli).toContain(command);
    }

    for (const dependency of [
      '"apps/desktop/**"',
      '"mcp/compatibility/blockbench.json"',
      '"mcp/distribution/**"',
    ]) expect(workflow).toContain(dependency);
  });

  test("Desktop versions and Rust toolchain stay synchronized", async () => {
    const [pkgText, cargoText, tauriText, toolchain] = await Promise.all([
      source("../apps/desktop/package.json"),
      source("../apps/desktop/src-tauri/Cargo.toml"),
      source("../apps/desktop/src-tauri/tauri.conf.json"),
      source("../apps/desktop/rust-toolchain.toml"),
    ]);
    const pkg = JSON.parse(pkgText) as { version: string };
    const cargo = Bun.TOML.parse(cargoText) as { package: { version: string } };
    const tauri = JSON.parse(tauriText) as { version: string };

    expect(cargo.package.version).toBe(pkg.version);
    expect(tauri.version).toBe(pkg.version);
    expect(pkgText).toContain('"license": "GPL-3.0-only"');
    expect(cargoText).toContain('license = "GPL-3.0-only"');
    expect(tauriText).toContain('"licenseFile": "../../../LICENSE"');
    expect(toolchain).toContain('channel = "1.98.1"');
  });

  test("Desktop generated Rust and icon outputs stay untracked", async () => {
    const ignore = await source("../.gitignore");
    expect(ignore).toContain("apps/desktop/src-tauri/target/");
    expect(ignore).toContain("apps/desktop/src-tauri/icons/");
  });

  test("Desktop bootstrap resource is generated by the canonical managed package pipeline", async () => {
    const [pkgText, bundleConfig, prep, ignore] = await Promise.all([
      source("../apps/desktop/package.json"),
      source("../apps/desktop/src-tauri/tauri.bundle.conf.json"),
      source("../apps/desktop/scripts/prepare-managed-resource.ps1"),
      source("../.gitignore"),
    ]);

    expect(pkgText).toContain("prepare:managed-resource");
    expect(pkgText).toContain("--config src-tauri/tauri.bundle.conf.json");
    expect(bundleConfig).toContain('"resources/managed/"');
    expect(prep).toContain("bun run ./distribution/package.ts");
    expect(prep).toContain("dist\\managed\\package");
    expect(prep).toContain("Managed bootstrap source SHA");
    expect(prep).toContain("Desktop source SHA");
    expect(ignore).toContain("apps/desktop/src-tauri/resources/managed/");
  });

  test("Desktop verification includes source proof and a Windows installer smoke build", async () => {
    const workflow = await source("../.github/workflows/desktop-verify.yml");
    expect(workflow).toContain("Parse Desktop PowerShell scripts");
    expect(workflow).toContain("System.Management.Automation.Language.Parser");
    expect(workflow).toContain("npm run verify:source");
    expect(workflow).toContain("npm run build:app");
    expect(workflow).toContain("Setup baseline Bun");
    expect(workflow).toContain("bun-windows-x64-baseline.zip");
    expect(workflow).toContain("lazydesigner-desktop-windows-x64");
    expect(workflow).toContain("bundle/nsis/*.exe");
    expect(workflow).toContain("SHA256SUMS.txt");
    expect(workflow).toContain("Silent-install Desktop and smoke bundled bootstrap");
    expect(workflow).toContain("Runtime TLS");
    expect(workflow).toContain("desktop-build-provenance.json");
  });

  test("Desktop preserves client-owned Gateway semantics", async () => {
    const [rust, readme] = await Promise.all([
      source("../apps/desktop/src-tauri/src/system_status.rs"),
      source("../apps/desktop/README.md"),
    ]);

    expect(rust).toContain('ownership: "client-owned"');
    expect(rust).toContain('state: "unknown"');
    expect(rust).toContain("Managed status is unavailable; refresh before maintenance.");
    expect(readme).toContain("Desktop therefore does not launch, restart, terminate, or watchdog Gateway processes.");
    expect(readme).not.toContain("Start Gateway command");
  });
});
