import { describe, expect, test } from "bun:test";

async function source(path: string): Promise<string> {
  return Bun.file(path).text();
}

describe("Desktop control-plane ownership", () => {
  test("Desktop depends on canonical compatibility and managed distribution owners", async () => {
    const [rust, app, cli, workflow] = await Promise.all([
      source("../apps/desktop/src-tauri/src/system_status.rs"),
      source("../apps/desktop/src/App.svelte"),
      source("distribution/cli.ts"),
      source("../.github/workflows/desktop-verify.yml"),
    ]);

    expect(rust).toContain('../../../../mcp/compatibility/blockbench.json');
    expect(rust).toContain('"update" | "rollback" | "recover" | "repair" | "setup-tls"');
    expect(rust).toContain('.arg("install")');
    expect(rust).toContain('"resources/managed/blockit.exe"');
    expect(rust).toContain('"--plugin-path"');
    expect(rust).toContain('join("plugins").join("blockit_mcp.js")');
    expect(app).toContain("ensure_ready");
    expect(app).toContain("show_plugin_file");
    expect(app).toContain("setup-tls");
    expect(app).toContain("runManagedAction('update')");
    expect(app).toContain("tls_ready");
    expect(app).toContain("'update' | 'rollback' | 'recover' | 'repair'");
    for (const command of ["update", "rollback", "recover", "repair", "status", "mcp"]) {
      expect(cli).toContain(command);
    }

    for (const dependency of [
      '"apps/desktop/**"',
      '"mcp/compatibility/blockbench.json"',
      '"mcp/distribution/**"',
    ]) expect(workflow).toContain(dependency);
  });

  test("Desktop versions and Rust toolchain stay synchronized", async () => {
    const [pkgText, cargoText, tauriText, toolchain] = await Promise.all([
      source("../apps/desktop/package.json"),
      source("../apps/desktop/src-tauri/Cargo.toml"),
      source("../apps/desktop/src-tauri/tauri.conf.json"),
      source("../apps/desktop/rust-toolchain.toml"),
    ]);
    const pkg = JSON.parse(pkgText) as { version: string };
    const cargo = Bun.TOML.parse(cargoText) as { package: { version: string } };
    const tauri = JSON.parse(tauriText) as { version: string };

    expect(cargo.package.version).toBe(pkg.version);
    expect(tauri.version).toBe(pkg.version);
    expect(pkgText).toContain('"license": "GPL-3.0-only"');
    expect(cargoText).toContain('license = "GPL-3.0-only"');
    expect(tauriText).toContain('"licenseFile": "../../../LICENSE"');
    expect(toolchain).toContain('channel = "1.98.1"');
  });

  test("Desktop generated Rust and icon outputs stay untracked", async () => {
    const ignore = await source("../.gitignore");
    expect(ignore).toContain("apps/desktop/src-tauri/target/");
    expect(ignore).toContain("apps/desktop/src-tauri/icons/");
  });

  test("Desktop bootstrap resource is generated by the canonical managed package pipeline", async () => {
    const [pkgText, bundleConfig, prep, ignore] = await Promise.all([
      source("../apps/desktop/package.json"),
      source("../apps/desktop/src-tauri/tauri.bundle.conf.json"),
      source("../apps/desktop/scripts/prepare-managed-resource.ps1"),
      source("../.gitignore"),
    ]);

    expect(pkgText).toContain("prepare:managed-resource");
    expect(pkgText).toContain("--config src-tauri/tauri.bundle.conf.json");
    expect(bundleConfig).toContain('"resources/managed/"');
    expect(prep).toContain("bun run ./distribution/package.ts");
    expect(prep).toContain("dist\\managed\\package");
    expect(prep).toContain("Managed bootstrap source SHA");
    expect(prep).toContain("Desktop source SHA");
    expect(ignore).toContain("apps/desktop/src-tauri/resources/managed/");
  });

  test("Desktop verification includes source proof and a Windows installer smoke build", async () => {
    const workflow = await source("../.github/workflows/desktop-verify.yml");
    expect(workflow).toContain("Parse Desktop PowerShell scripts");
    expect(workflow).toContain("System.Management.Automation.Language.Parser");
    expect(workflow).toContain("npm run verify:source");
    expect(workflow).toContain("npm run build:app");
    expect(workflow).toContain("Setup baseline Bun");
    expect(workflow).toContain("bun-windows-x64-baseline.zip");
    expect(workflow).toContain("lazydesigner-desktop-windows-x64");
    expect(workflow).toContain("bundle/nsis/*.exe");
    expect(workflow).toContain("SHA256SUMS.txt");
    expect(workflow).toContain("Silent-install Desktop and smoke bundled bootstrap");
    expect(workflow).toContain("Runtime TLS");
    expect(workflow).toContain("setup-tls --root");
    expect(workflow).toContain("Runtime TLS setup ignored an active Gateway lease");
    expect(workflow).toContain("Explicit Runtime TLS renewal did not return TLS_READY");
    expect(workflow).toContain("desktop-build-provenance.json");
  });

  test("Desktop preserves client-owned Gateway semantics", async () => {
    const [rust, readme] = await Promise.all([
      source("../apps/desktop/src-tauri/src/system_status.rs"),
      source("../apps/desktop/README.md"),
    ]);

    expect(rust).toContain('ownership: "client-owned"');
    expect(rust).toContain('state: "unknown"');
    expect(rust).toContain("Managed status is unavailable; refresh before maintenance.");
    expect(readme).toContain("Desktop therefore does not launch, restart, terminate, or watchdog Gateway processes.");
    expect(rust).toContain("pub fn ensure_ready");
    expect(rust).toContain("manual_plugin_approval_recommended");
    expect(rust).toContain("PLUGIN_INTEGRITY");
    expect(readme).not.toContain("Start Gateway command");
  });
  test("Desktop observability keeps bounded readiness outcomes", async () => {
    const [main, log, runbook] = await Promise.all([
      source("../apps/desktop/src-tauri/src/main.rs"),
      source("../apps/desktop/src-tauri/src/operation_log.rs"),
      source("../docs/05-operations/local-acceptance-runbook.md"),
    ]);

    expect(main).toContain('operation_log::record("ensure_ready", value.status)');
    expect(main).toContain('operation_log::record("ensure_ready", value.reason)');
    expect(main).toContain('.get("status")');
    expect(log).toContain("MAX_LOG_BYTES");
    expect(runbook).toContain("Desktop Control Plane Acceptance");
    expect(runbook).toContain("managed plugin modified");
    expect(runbook).toContain("transient fast-probe failure");
  });

  test("Desktop UI uses one canonical workstation readiness path", async () => {
    const [app, main, rust] = await Promise.all([
      source("../apps/desktop/src/App.svelte"),
      source("../apps/desktop/src-tauri/src/main.rs"),
      source("../apps/desktop/src-tauri/src/system_status.rs"),
    ]);

    expect(app).toContain("invoke<EnsureReadyResult>('ensure_ready')");
    expect(app).not.toContain("invoke<BlockbenchActionResult>('open_blockbench')");
    expect(main).not.toContain("fn open_blockbench()");
    expect(rust).toContain("open_blockbench()?");
    expect(app).toContain("value.plugin_integrity === 'modified'");
    expect(app).toContain("next.managed = fixture === 'fresh-install' ? null :");
    expect(app).toContain("invoke<ConnectionStatus>('connection_status')");
    expect(app).toContain("value.product_state");
    expect(rust).toContain("fn project_product_state(");
    expect(rust).toContain("TcpStream::connect_timeout");
    expect(rust).toContain("gateway_active_fast");
    expect(rust).not.toContain('"Managed connection status"');

    expect(app).toContain("async function connectBlockbench() {\n    if (devFixture) return;");
    expect(app).toContain("async function installLazyDesigner() {\n    if (devFixture) return;");
    expect(app).toContain("async function runManagedAction(action:");

  });
});


describe("Desktop release/version contract", () => {
  test("draft release stays explicit, exact-versioned, and separate from managed-component updates", async () => {
    const [workflow, releaseConfig, signScript, importScript, manifestScript, releaseChannel] = await Promise.all([
      source("../.github/workflows/desktop-draft-release.yml"),
      source("../apps/desktop/src-tauri/tauri.release.conf.json"),
      source("../apps/desktop/scripts/sign-windows.ps1"),
      source("../apps/desktop/scripts/import-windows-signing-certificate.ps1"),
      source("../apps/desktop/scripts/write-update-manifest.ps1"),
      source("../apps/desktop/release-channel.json"),
    ]);

    expect(workflow).toContain("workflow_dispatch:");
    expect(workflow).toContain("if: github.ref == 'refs/heads/main'");
    expect(workflow).toContain("desktop-v${{ inputs.version }}");
    expect(workflow).toContain("desktop-dev-v${{ inputs.version }}-$shortSha");
    expect(workflow).toContain("--prerelease");
    expect(workflow).toContain("Requested Desktop version");
    expect(workflow).toContain("does not match source version");
    expect(workflow).toContain("npm run verify:source");
    expect(workflow).toContain("npm run build:app");
    expect(workflow).toContain("npm run build:app:trusted");
    expect(workflow).toContain("Get-AuthenticodeSignature");
    expect(workflow).toContain("TAURI_SIGNING_PRIVATE_KEY");
    expect(workflow).toContain("DEVELOPMENT DRAFT");
    expect(workflow).toContain("TRUSTED DRAFT");
    expect(releaseConfig).toContain('"createUpdaterArtifacts": true');
    expect(releaseConfig).toContain("sign-windows.ps1");
    expect(signScript).toContain("LAZYDESIGNER_WINDOWS_CERT_THUMBPRINT");
    expect(signScript).toContain("signtool.exe");
    expect(importScript).toContain("Import-PfxCertificate");
    expect(manifestScript).toContain("windows-x86_64");
    expect(manifestScript).toContain("signature = $signature");
    expect(releaseChannel).toContain('"manifestAsset": "latest.json"');
    expect(releaseChannel).toContain('"selfUpdateRuntimeEnabled": false');
    expect(workflow).toContain("write-update-manifest.ps1");
    expect(workflow).toContain("latest.json");
    expect(workflow).toContain("Bundled managed source SHA");
    expect(workflow).toContain("desktop-build-provenance.json");
    expect(workflow).toContain("SHA256SUMS.txt");
    expect(workflow).toContain("--draft");
    expect(workflow).toContain("nothing was auto-published");
    expect(workflow).not.toContain("tauri-plugin-updater");
    expect(releaseConfig).not.toContain('"plugins"');
  });
});
